#!/usr/bin/env python3
"""Bundle awslens' local modules into standalone Python source files.

Third-party dependencies are intentionally not bundled.  Install them in the
target environment with ``pip install boto3 pyyaml`` before running an output
file.
"""

from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
from pprint import pformat


PROJECT_ROOT = Path(__file__).resolve().parents[1]
LOCAL_PACKAGES = ("core", "fetchers")


def read_local_modules() -> tuple[dict[str, str], set[str]]:
    """Return importable names and source for the project's local packages."""
    modules: dict[str, str] = {}
    packages: set[str] = set()

    for package in LOCAL_PACKAGES:
        package_dir = PROJECT_ROOT / package
        for path in sorted(package_dir.rglob("*.py")):
            relative = path.relative_to(PROJECT_ROOT).with_suffix("")
            parts = relative.parts
            if parts[-1] == "__init__":
                module_name = ".".join(parts[:-1])
                packages.add(module_name)
            else:
                module_name = ".".join(parts)

            source = path.read_text(encoding="utf-8")
            compile(source, str(path), "exec")
            modules[module_name] = source

    return modules, packages


def bootstrap(modules: dict[str, str], packages: set[str]) -> str:
    """Create a small in-memory importer for the bundled local modules."""
    return f'''# Generated by scripts/build_single_file.py. Do not edit directly.
# External dependencies are deliberately not bundled: boto3, PyYAML.
import importlib.abc
import importlib.util
import sys

_BUNDLED_MODULES = {pformat(modules, width=100, sort_dicts=True)}
_BUNDLED_PACKAGES = {pformat(packages, width=100)}


class _BundledModuleLoader(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _BUNDLED_MODULES:
            return None
        return importlib.util.spec_from_loader(
            fullname, self, is_package=fullname in _BUNDLED_PACKAGES,
        )

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        name = module.__name__
        module.__file__ = f"<bundled {{name}}>"
        if name in _BUNDLED_PACKAGES:
            module.__path__ = []
        exec(compile(_BUNDLED_MODULES[name], module.__file__, "exec"), module.__dict__)


sys.meta_path.insert(0, _BundledModuleLoader())

'''


def build(entry_name: str, destination: Path, modules: dict[str, str], packages: set[str]) -> None:
    entry_path = PROJECT_ROOT / entry_name
    entry_source = entry_path.read_text(encoding="utf-8")
    compile(entry_source, str(entry_path), "exec")
    destination.write_text(bootstrap(modules, packages) + entry_source, encoding="utf-8")
    destination.chmod(0o755)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build self-contained awslens Python source files (excluding third-party dependencies).",
    )
    parser.add_argument(
        "--output-dir", type=Path, default=PROJECT_ROOT / "dist",
        help="Directory for generated files (default: %(default)s)",
    )
    args = parser.parse_args()

    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    modules, packages = read_local_modules()

    build("awslens.py", output_dir / "awslens.py", modules, packages)
    build("awslens_diff.py", output_dir / "awslens-diff.py", modules, packages)
    print(f"Built {output_dir / 'awslens.py'}")
    print(f"Built {output_dir / 'awslens-diff.py'}")


if __name__ == "__main__":
    main()
